{
  "title": "Struct tokio::runtime::TryCurrentError",
  "sections": [
    {
      "name": "implementations",
      "methods": [
        {
          "code": "pub fn is_missing_context(&self) -> bool",
          "text": "Returns true if the call failed because there is currently no runtime in the Tokio context."
        },
        {
          "code": "pub fn is_thread_local_destroyed(&self) -> bool",
          "text": "Returns true if the call failed because the Tokio context thread-local had been destroyed. This can usually only happen if in the destructor of other thread-locals."
        }
      ]
    },
    {
      "name": "derefMethods",
      "methods": []
    },
    {
      "name": "traitImpl",
      "traits": [
        {
          "title": "impl Debug for TryCurrentError",
          "methods": [
            {
              "code": "fn fmt(&self, f: &mut Formatter<'_>) -> Result",
              "text": "Formats the value using the given formatter."
            }
          ]
        },
        {
          "title": "impl Display for TryCurrentError",
          "methods": [
            {
              "code": "fn fmt(&self, f: &mut Formatter<'_>) -> Result",
              "text": "Formats the value using the given formatter."
            }
          ]
        },
        {
          "title": "impl Error for TryCurrentError",
          "methods": [
            {
              "code": "fn source(&self) -> Option<&(dyn Error + 'static)>",
              "text": "The lower-level source of this error, if any."
            },
            {
              "code": "fn backtrace(&self) -> Option<&Backtrace>",
              "text": "Returns a stack backtrace, if available, of where this error occurred."
            }
          ]
        }
      ]
    }
  ]
}